baseUrl: http://65.21.149.91/
url:
  promo: promo/
  invoice: invoice/

report:
  output:
    # Dev Path
#    invoice: /home/reports/invoice/
    # Local Path For Testing Purposes
    invoice: src/main/resources/out/