pipeline {
    agent any
    stages {

        stage('Checkout Codebase') {
            steps {
            checkout scm: [$class: 'GitSCM',
             userRemoteConfigs: [[credentialsId: 'secret',url: 'https://github.com/jeffreylim17/invoice.git']]]

            }
        }
        stage('Build') {
            steps {
               sh "mvn clean package"
            }
        }

        stage('Test') {
            steps {
                sh "mvn clean install"
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Done!'
            }
        }
    }
}

